#!/usr/bin/env python
# coding: utf-8

# ## Dynamic Modelling Introduction
# 
# The goal of this section is to analyse multiple annual reports per company to understand how companies may have changed in business direction or target industries over multiple years. 
# 
# We explore two types of dynamic modelling:  
# 
# 1. Look at differences year over year in word embeddings generated by TD-IDF, Word2Vec and Doc2Vec. We take the difference between the word embedding vectors of two distinct years and evaluate the addition/reduction in certain vocabulary.
#     - This work can be found [here](https://richardye101.github.io/ubineer_nlp_research/content/richard/8_Dynamic_Embedding.html)
# 
# 
# 2. Look at differences year over year in topics generated by Non-Negative Matrix Factorization(NMF), Latent Dirichlet Allocation (LDA), and Latent Semantic Analysis (LSA). We take the difference between the document-topic vectors and evaluate the addition/reduction in certain topics.
#     - This work can be found [here](https://richardye101.github.io/ubineer_nlp_research/content/mary/Report_Topic_Modelling.html)
